//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.BILLINFOes = new HashSet<BILLINFO>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> SIM { get; set; }
        public Nullable<int> MemoryStorage { get; set; }
        public Nullable<int> Ram { get; set; }
        public string Picture { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> OSID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLINFO> BILLINFOes { get; set; }
        public virtual BRAND BRAND { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
